name: Bug report
description: Reportar um bug no Chess
labels: ["bug"]

body:
  - type: input
    id: environment
    attributes:
      label: Ambiente
      description: Informe seu sistema operacional e versão do Java.
      placeholder: Ex.: Windows 11, Java 17
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versão/commit
      description: Informe a versão ou commit em que o bug ocorreu.
      placeholder: Ex.: v1.0.2 ou hash do commit
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Descrição do bug
      description: Explique o problema em detalhe.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Passos para reproduzir
      description: Liste os passos necessários para reproduzir o bug.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/stacktrace
      description: Inclua logs ou stacktrace relevantes, se disponíveis.
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: Confirmações
      description: Marque as opções abaixo.
      options:
        - label: Estou usando a versão mais recente do Chess.
          required: true
        - label: Verifiquei que este bug não foi reportado em issues abertas ou fechadas.
          required: true