name: Release

on:
  push:
    tags:
      - 'v*'   # dispara quando criamos uma tag começando com v (ex.: v1.0.0)

permissions:
  contents: write   # necessário para criar/atualizar releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Verify Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build JAR
        run: ./gradlew clean build --stacktrace --no-daemon

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar